import { Lato, Noto_Sans } from "next/font/google";
// import "./globals.css";
import "./styles/style.scss";

const lato = Lato({
  variable: "--lato",
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
});

const notoSans = Noto_Sans({
  variable: "--notoSans",
  subsets: ["latin"],
});

export const metadata = {
  title: "派庫廚房版型",
  description: "Generated by create next app",
  robots: {
    index: false,
    follow: false,
    nocache: true,
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${lato.variable} ${notoSans.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
